eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.web: INFO
    com.dong: DEBUG
    org.hibernate: INFO 